project_id = "ifpqrugbpzqpapoaameo"

[functions.ensure-admin-exists]
verify_jwt = false

[functions.sync-temporary-password]
verify_jwt = false

[functions.create-missing-auth-user]
verify_jwt = false