project_id = "ifpqrugbpzqpapoaameo"

[functions.ensure-admin-exists]
verify_jwt = false

[functions.sync-temporary-password]
verify_jwt = false

[functions.sync-admin-password]
verify_jwt = false

[functions.create-missing-auth-user]
verify_jwt = false

[functions.create-admin-auth-user]
verify_jwt = false

[functions.update-admin-auth-email]
verify_jwt = false

[functions.delete-admin-auth-user]
verify_jwt = false